import RenderOnClient from '@/helpers/RenderOnClient';
import '@/scss/styles.scss';
import { CssBaseline } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog - Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RenderOnClient>
          <CssBaseline />
        </RenderOnClient>
        {children}
      </body>
    </html>
  );
}
